### ISSUE TITLE
How to stop Chromium process after Eclipse shutdown?

### ISSUE THREAD

**Issue by longjohnhard** [maketechnology/chromium.swt#43] opened 2019-01-28 14:06 UTC
When closing the eclipse, the chromium process (chromium_subp-0700.exe) keeps running.
This prevents the eclipse from being terminated.  

I already tried to use the Chromium.shutdown(); method, but it seems to be protected and can't be used.

What's the proper procedure to terminate chromium?

Chromium for SWT is a great thing that I'm sure many people have been waiting for.
I hope you can help me.

thx

**Comment by gzunino** [comment] 2019-01-30 05:47
Hi could you re test with new version 0.8.0.  The process should close itself when the main java process exists.

**Comment by longjohnhard** [comment] 2019-01-31 11:19
I tested the new version. Unfortunately the problem still exists. We use chromium within an eclipse rcp application for windows. When closing the application the browser widget gets disposed but the chromium process (chromium_subp-0801.exe) is still running. In an older version of chromium we used the Chromium.shutdown(); method to kill the process. This is not possible anymore because the class/method is protected.

**Comment by gzunino** [comment] 2019-01-31 13:44
Could you share a minimal example that reproduces the problem.  Or the last lines of stdout, from "disposing chromium" to the end. Thanks

**Comment by gzunino** [comment] 2019-04-25 03:36
@longjohnhard is this still a problem with 0.9.0 ?

**Comment by vel144** [comment] 2019-07-11 08:34
@gzunino yes the problem still exists. How to resolve this?

**Comment by gzunino** [comment] 2019-07-26 06:14
@longjohnhard could you please retes on 0.10.0. We changed most of the closing and disposing of instances. I cant reproduce. Please share an example if you still face it. All subprocess are closed when the JVM exits.

**Closed by gzunino** 2019-07-26 06:14 UTC
