### ISSUE TITLE
Various crashes in com.kenai.jffi.Foreign.memchr(JIJ)J+0

### ISSUE THREAD

**Issue by parg** [maketechnology/chromium.swt#42] opened 2019-01-15 20:24 UTC
Same setup as in https://github.com/maketechnology/chromium.swt/issues/41

I was testing in BiglyBT with an embedded browser showing https://biglybt.tumblr.com/ and after a few refreshes (triggered by clicking on the large, bold "BiglyBT" top left) it crashes the application. I went ahead and created a standalone test

			Browser browser = new Browser( shell, SWT.NULL );
			browser.setUrl( "https://biglybt.tumblr.com/" );
			shell.open();

and the same thing happens. I also created a refresh loop calling browser.refresh() every 10 seconds and this also produces the crash.

Here are a few stack traces - please ask if I can help further!

<hr>
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [msvcrt.dll+0x15001]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.kenai.jffi.Foreign.memchr(JIJ)J+0
j  com.kenai.jffi.MemoryIO$UnsafeImpl.memchr(JIJ)J+4
j  com.kenai.jffi.MemoryIO.indexOf(JBI)J+6
j  jnr.ffi.provider.jffi.DirectMemoryIO.indexOf(JBI)I+12
j  jnr.ffi.provider.AbstractMemoryIO.indexOf(JB)I+5
j  jnr.ffi.provider.converters.StringResultConverter.fromNative(Ljnr/ffi/Pointer;Ljnr/ffi/mapper/FromNativeContext;)Ljava/lang/String;+13
j  org.eclipse.swt.chromium.Chromium$Lib$jnr$ffi$0.cefswt_get_text(Ljnr/ffi/Pointer;Lorg/eclipse/swt/internal/chromium/CEF$cef_string_visitor_t;)Ljava/lang/String;+78
j  org.eclipse.swt.chromium.Chromium.updateText()V+36
j  org.eclipse.swt.chromium.Chromium.lambda$13(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;Ljnr/ffi/Pointer;I)V+19
j  org.eclipse.swt.chromium.Chromium$$Lambda$360.invoke(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;Ljnr/ffi/Pointer;I)V+9
j  jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$28.invoke(JJJI)V+49
v  ~StubRoutines::call_stub
J 9375  com.kenai.jffi.Foreign.invokeArrayReturnInt(JJ[B)I (0 bytes) @ 0x0000000004260cdd [0x0000000004260c80+0x5d]
J 11181 C2 com.kenai.jffi.Invoker.invokeInt(Lcom/kenai/jffi/CallContext;JLcom/kenai/jffi/HeapInvocationBuffer;)I (42 bytes) @ 0x0000000002f67808 [0x0000000002f677a0+0x68]
J 9954 C1 org.eclipse.swt.chromium.Chromium$$Lambda$335.run()V (8 bytes) @ 0x0000000004471084 [0x0000000004470a60+0x624]
J 10266 C2 org.eclipse.swt.widgets.Display.readAndDispatch()Z (96 bytes) @ 0x0000000002b82c3c [0x0000000002b81fa0+0xc9c]
J 14129% C2 com.biglybt.ui.swt.mainwindow.SWTThread.<init>(Lcom/biglybt/ui/IUIIntializer;)V (883 bytes) @ 0x00000000057687b4 [0x0000000005768320+0x494]
j  com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(Lcom/biglybt/ui/IUIIntializer;)V+18
j  com.biglybt.ui.swt.Initializer.<init>(Lcom/biglybt/core/Core;Lcom/biglybt/ui/common/StartServer;)V+121
j  com.biglybt.ui.swt.UI.takeMainThread()V+8
j  com.biglybt.ui.Main.main([Ljava/lang/String;)V+690

<hr>
C  [msvcrt.dll+0x15001]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.kenai.jffi.Foreign.memchr(JIJ)J+0
J 11779 C1 jnr.ffi.provider.jffi.DirectMemoryIO.indexOf(JBI)I (17 bytes) @ 0x0000000004ce386c [0x0000000004ce3560+0x30c]
J 11778 C1 jnr.ffi.provider.AbstractMemoryIO.indexOf(JB)I (9 bytes) @ 0x0000000002891fe4 [0x0000000002891ec0+0x124]
J 11051 C1 jnr.ffi.provider.converters.StringResultConverter.fromNative(Ljnr/ffi/Pointer;Ljnr/ffi/mapper/FromNativeContext;)Ljava/lang/String; (110 bytes) @ 0x00000000048019cc [0x0000000004801640+0x38c]
j  org.eclipse.swt.chromium.Chromium$Lib$jnr$ffi$0.cefswt_get_text(Ljnr/ffi/Pointer;Lorg/eclipse/swt/internal/chromium/CEF$cef_string_visitor_t;)Ljava/lang/String;+78
j  org.eclipse.swt.chromium.Chromium.updateText()V+36
j  org.eclipse.swt.chromium.Chromium.lambda$13(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;Ljnr/ffi/Pointer;I)V+19
j  org.eclipse.swt.chromium.Chromium$$Lambda$338.invoke(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;Ljnr/ffi/Pointer;I)V+9
j  jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$28.invoke(JJJI)V+49
v  ~StubRoutines::call_stub
J 6831  com.kenai.jffi.Foreign.invokeArrayReturnInt(JJ[B)I (0 bytes) @ 0x0000000002877a9d [0x0000000002877a40+0x5d]
J 11405 C2 org.eclipse.swt.chromium.Chromium$$Lambda$313.run()V (8 bytes) @ 0x0000000004b00894 [0x0000000004b00620+0x274]
J 7184 C2 org.eclipse.swt.widgets.Display.readAndDispatch()Z (96 bytes) @ 0x0000000002b75cf0 [0x0000000002b75180+0xb70]
j  com.biglybt.ui.swt.mainwindow.SWTThread.<init>(Lcom/biglybt/ui/IUIIntializer;)V+601
j  com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(Lcom/biglybt/ui/IUIIntializer;)V+18
j  com.biglybt.ui.swt.Initializer.<init>(Lcom/biglybt/core/Core;Lcom/biglybt/ui/common/StartServer;)V+121
j  com.biglybt.ui.swt.UI.takeMainThread()V+8
j  com.biglybt.ui.Main.main([Ljava/lang/String;)V+690

<hr>
C  [msvcrt.dll+0x15001]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.kenai.jffi.Foreign.memchr(JIJ)J+0
j  com.kenai.jffi.MemoryIO$UnsafeImpl.memchr(JIJ)J+4
j  com.kenai.jffi.MemoryIO.indexOf(JBI)J+6
j  jnr.ffi.provider.jffi.DirectMemoryIO.indexOf(JBI)I+12
j  jnr.ffi.provider.AbstractMemoryIO.indexOf(JB)I+5
J 11883 C1 jnr.ffi.provider.converters.StringResultConverter.fromNative(Ljnr/ffi/Pointer;Ljnr/ffi/mapper/FromNativeContext;)Ljava/lang/String; (110 bytes) @ 0x0000000004dca30c [0x0000000004dc9f80+0x38c]
j  org.eclipse.swt.chromium.Chromium$Lib$jnr$ffi$0.cefswt_get_text(Ljnr/ffi/Pointer;Lorg/eclipse/swt/internal/chromium/CEF$cef_string_visitor_t;)Ljava/lang/String;+78
j  org.eclipse.swt.chromium.Chromium.updateText()V+36
j  org.eclipse.swt.chromium.Chromium.lambda$13(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;Ljnr/ffi/Pointer;I)V+19
j  org.eclipse.swt.chromium.Chromium$$Lambda$370.invoke(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;Ljnr/ffi/Pointer;I)V+9
j  jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$28.invoke(JJJI)V+49
v  ~StubRoutines::call_stub
J 10647  com.kenai.jffi.Foreign.invokeArrayReturnInt(JJ[B)I (0 bytes) @ 0x000000000484bb5d [0x000000000484bb00+0x5d]
J 11998 C2 com.kenai.jffi.Invoker.invokeInt(Lcom/kenai/jffi/CallContext;JLcom/kenai/jffi/HeapInvocationBuffer;)I (42 bytes) @ 0x0000000004dd240c [0x0000000004dd23a0+0x6c]
J 10666 C1 org.eclipse.swt.chromium.Chromium$$Lambda$345.run()V (8 bytes) @ 0x00000000048a8884 [0x00000000048a8260+0x624]
J 10672 C2 org.eclipse.swt.widgets.Display.readAndDispatch()Z (96 bytes) @ 0x00000000048c6198 [0x00000000048c58e0+0x8b8]
j  com.biglybt.ui.swt.mainwindow.SWTThread.<init>(Lcom/biglybt/ui/IUIIntializer;)V+601
j  com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(Lcom/biglybt/ui/IUIIntializer;)V+18
j  com.biglybt.ui.swt.Initializer.<init>(Lcom/biglybt/core/Core;Lcom/biglybt/ui/common/StartServer;)V+121
j  com.biglybt.ui.swt.UI.takeMainThread()V+8
j  com.biglybt.ui.Main.main([Ljava/lang/String;)V+690

<hr>
C  [msvcrt.dll+0x15001]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 1210  com.kenai.jffi.Foreign.memchr(JIJ)J (0 bytes) @ 0x000000000282cb49 [0x000000000282cb00+0x49]
J 1181 C1 jnr.ffi.provider.jffi.DirectMemoryIO.indexOf(JBI)I (17 bytes) @ 0x000000000271824c [0x0000000002717f60+0x2ec]
J 1180 C1 jnr.ffi.provider.AbstractMemoryIO.indexOf(JB)I (9 bytes) @ 0x000000000277dec4 [0x000000000277ddc0+0x104]
J 1157 C1 jnr.ffi.provider.converters.StringResultConverter.fromNative(Ljnr/ffi/Pointer;Ljnr/ffi/mapper/FromNativeContext;)Ljava/lang/String; (110 bytes) @ 0x0000000002626554 [0x00000000026261e0+0x374]
j  org.eclipse.swt.chromium.Chromium$Lib$jnr$ffi$0.cefswt_get_text(Ljnr/ffi/Pointer;Lorg/eclipse/swt/internal/chromium/CEF$cef_string_visitor_t;)Ljava/lang/String;+78
j  org.eclipse.swt.chromium.Chromium.updateText()V+36
j  org.eclipse.swt.chromium.Chromium.lambda$13(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;Ljnr/ffi/Pointer;I)V+19
j  org.eclipse.swt.chromium.Chromium$$Lambda$34.invoke(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;Ljnr/ffi/Pointer;I)V+9
j  jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$28.invoke(JJJI)V+49
v  ~StubRoutines::call_stub
J 1039  com.kenai.jffi.Foreign.invokeArrayReturnInt(JJ[B)I (0 bytes) @ 0x0000000002806a1d [0x00000000028069c0+0x5d]
J 1205 C2 org.eclipse.swt.chromium.Chromium$$Lambda$9.run()V (8 bytes) @ 0x0000000002830bb0 [0x0000000002830a00+0x1b0]
J 1118 C2 org.eclipse.swt.widgets.Display.readAndDispatch()Z (96 bytes) @ 0x0000000002868e04 [0x00000000028688e0+0x524]
j  a.b.c.Test.main([Ljava/lang/String;)V+77

<hr>
C  [msvcrt.dll+0x15001]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 1181  com.kenai.jffi.Foreign.memchr(JIJ)J (0 bytes) @ 0x00000000028105c9 [0x0000000002810580+0x49]
J 1153 C1 jnr.ffi.provider.jffi.DirectMemoryIO.indexOf(JBI)I (17 bytes) @ 0x00000000026de54c [0x00000000026de260+0x2ec]
J 1152 C1 jnr.ffi.provider.AbstractMemoryIO.indexOf(JB)I (9 bytes) @ 0x00000000026deb44 [0x00000000026dea40+0x104]
J 1124 C1 jnr.ffi.provider.converters.StringResultConverter.fromNative(Ljnr/ffi/Pointer;Ljnr/ffi/mapper/FromNativeContext;)Ljava/lang/String; (110 bytes) @ 0x0000000002618dd4 [0x0000000002618a60+0x374]
j  org.eclipse.swt.chromium.Chromium$Lib$jnr$ffi$0.cefswt_get_text(Ljnr/ffi/Pointer;Lorg/eclipse/swt/internal/chromium/CEF$cef_string_visitor_t;)Ljava/lang/String;+78
j  org.eclipse.swt.chromium.Chromium.updateText()V+36
j  org.eclipse.swt.chromium.Chromium.lambda$13(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;Ljnr/ffi/Pointer;I)V+19
j  org.eclipse.swt.chromium.Chromium$$Lambda$34.invoke(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;Ljnr/ffi/Pointer;I)V+9
j  jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$28.invoke(JJJI)V+49
v  ~StubRoutines::call_stub
J 1008  com.kenai.jffi.Foreign.invokeArrayReturnInt(JJ[B)I (0 bytes) @ 0x00000000027e77dd [0x00000000027e7780+0x5d]
J 1189 C2 org.eclipse.swt.chromium.Chromium$$Lambda$9.run()V (8 bytes) @ 0x00000000027bd6b0 [0x00000000027bd500+0x1b0]
J 1096 C2 org.eclipse.swt.widgets.Display.readAndDispatch()Z (96 bytes) @ 0x000000000284adc4 [0x000000000284a8a0+0x524]
j  a.b.c.Test.main([Ljava/lang/String;)V+89

**Comment by gzunino** [comment] 2019-01-30 05:49
Hi, I think this should be fixed with new version 0.8.0. Please re test and close it fixed. Thanks, and we are very active! :)

**Comment by parg** [comment] 2019-01-30 10:44
Hi, sorry got the comment about being inactive! I grabbed the latest version and my test ran for quite a while before failing with something similar:

```Stack: [0x0000000001ef0000,0x0000000001ff0000],  sp=0x0000000001fea8a8,  free space=1002k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [msvcrt.dll+0x15001]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.kenai.jffi.Foreign.memchr(JIJ)J+0
J 1496 C1 jnr.ffi.provider.jffi.DirectMemoryIO.indexOf(JBI)I (17 bytes) @ 0x00000000029d0aac [0x00000000029d07a0+0x30c]
J 1495 C1 jnr.ffi.provider.AbstractMemoryIO.indexOf(JB)I (9 bytes) @ 0x0000000002615124 [0x0000000002615000+0x124]
J 1464 C1 jnr.ffi.provider.converters.StringResultConverter.fromNative(Ljnr/ffi/Pointer;Ljnr/ffi/mapper/FromNativeContext;)Ljava/lang/String; (110 bytes) @ 0x0000000002a1148c [0x0000000002a11100+0x38c]
j  org.eclipse.swt.chromium.Chromium$Lib$jnr$ffi$0.cefswt_get_text(Ljnr/ffi/Pointer;Lorg/eclipse/swt/internal/chromium/CEF$cef_string_visitor_t;)Ljava/lang/String;+78
j  org.eclipse.swt.chromium.Chromium.updateText()V+44
j  org.eclipse.swt.chromium.Chromium.lambda$20(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;III)V+71
j  org.eclipse.swt.chromium.Chromium$$Lambda$33.invoke(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;III)V+11
j  jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$27.invoke(JJIII)V+44
v  ~StubRoutines::call_stub
J 1297  com.kenai.jffi.Foreign.invokeArrayReturnInt(JJ[B)I (0 bytes) @ 0x00000000029d851d [0x00000000029d84c0+0x5d]
J 1428 C2 org.eclipse.swt.widgets.Display.readAndDispatch()Z (96 bytes) @ 0x00000000026898f4 [0x0000000002689200+0x6f4]
j  a.b.c.Test.main([Ljava/lang/String;)V+89
v  ~StubRoutines::call_stub

...
0x000007fec5900000 - 0x000007fec5a58000 	C:\Users\Paul\eclipse-oxygen-workspace\ChromeSWTTest\chromium-3071\chromium_swt-0800.dll
0x000007feafee0000 - 0x000007feb7392000 	C:\Users\Paul\eclipse-oxygen-workspace\ChromeSWTTest\chromium-3071\libcef.dll
0x000007fef1a20000 - 0x000007fef1ac1000 	C:\Users\Paul\eclipse-oxygen-workspace\ChromeSWTTest\chromium-3071\chrome_elf.dll
...


```

Please tell me if you need any further information!

**Comment by parg** [comment] 2019-01-31 16:01
Did you mean to close this? Still crashing for me on 0.8.1...

**Comment by parg** [comment] 2019-01-31 17:35
I spent a bit of time trying to recreate it on a Linux VM (checked out 'master' just as I did on Windows). It didn't crash but after quite a lot of refreshes it ground somewhat to a halt with occasional debugs like

```
J1:main:CALLBACK OnGotFocus (https://biglybt.tumblr.com/)
J1:main:on_before_browse:https://biglybt.tumblr.com/ (https://biglybt.tumblr.com/)
[0131/172055.601055:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1
CONTEXT CREATED
J1:main:on_address_change to https://biglybt.tumblr.com/ main (https://biglybt.tumblr.com/)
J1:main:on_before_browse:https://biglybt.tumblr.com/ (https://biglybt.tumblr.com/)
```

So I made a .jar from the chromium.swt project in the Linux VM and copied this back to my Windows 7 machine, just in case there was something weird going on, and ran the test

```
			final Display display = new Display();
			final Shell shell = new Shell(display);
			shell.setText("Chrome test");
	
			shell.setLayout( new GridLayout());
			
			Browser browser = new Browser( shell, SWT.NULL );
			
			browser.setLayoutData( new GridData( GridData.FILL_BOTH ));
			
			String url = "https://biglybt.tumblr.com/";		
			
			browser.setUrl( url );

			new Thread()
			{
				public void
				run()
				{
					while( true ){
						
						try{
							Thread.sleep( 10*1000 );
							
							display.asyncExec(
								new Runnable()
								{
									public void
									run()
									{
										browser.refresh();
									}
								});
							
						}catch( Throwable e ){
							
							e.printStackTrace();
						}
					}
				}
			}.start();
			
			shell.open();
			
			while(!shell.isDisposed()) {
				if (!display.readAndDispatch()) display.sleep();
			}
```
and after a while it crashed:

```
J1:main:text visited completed (https://biglybt.tumblr.com/)
J1:main:progress completed (https://biglybt.tumblr.com/)
J1:main:on_loading_state_change 1 (https://biglybt.tumblr.com/)
J1:main:update text (https://biglybt.tumblr.com/)
J1:main:progress changed (https://biglybt.tumblr.com/)
J1:main:on_before_browse:https://biglybt.tumblr.com/ (https://biglybt.tumblr.com/)
J1:main:text visited completed (https://biglybt.tumblr.com/)
J1:main:on_address_change to https://biglybt.tumblr.com/ main (https://biglybt.tumblr.com/)
J1:main:on_title_change: BiglyBT (https://biglybt.tumblr.com/)
[0131/173019.587:INFO:CONSOLE(29)] "Uncaught (in promise) TypeError: Cannot read property 'type' of undefined", source: https://assets.tumblr.com/client/prod/standalone/tumblelog/index.build.js?_v=92db2be43f74ecacde2e1349866393ce (29)
[0131/173019.587:INFO:CONSOLE(29)] "Uncaught (in promise) TypeError: Cannot read property 'type' of undefined", source: https://assets.tumblr.com/client/prod/standalone/tumblelog/index.build.js?_v=92db2be43f74ecacde2e1349866393ce (29)
[0131/173019.700:WARNING:spdy_session.cc(2857)] Received WINDOW_UPDATE for invalid stream 99
J1:main:on_loading_state_change 0 (https://biglybt.tumblr.com/)
J1:main:update text (https://biglybt.tumblr.com/)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000007fefe865001, pid=296520, tid=0x00000000000410a0
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [msvcrt.dll+0x15001]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Paul\eclipse-oxygen-workspace\ChromeSWTTest\hs_err_pid296520.log




Stack: [0x0000000002090000,0x0000000002190000],  sp=0x000000000218a328,  free space=1000k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [msvcrt.dll+0x15001]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.kenai.jffi.Foreign.memchr(JIJ)J+0
j  com.kenai.jffi.MemoryIO$UnsafeImpl.memchr(JIJ)J+4
j  com.kenai.jffi.MemoryIO.indexOf(JBI)J+6
j  jnr.ffi.provider.jffi.DirectMemoryIO.indexOf(JBI)I+12
j  jnr.ffi.provider.AbstractMemoryIO.indexOf(JB)I+5
J 1246 C1 jnr.ffi.provider.converters.StringResultConverter.fromNative(Ljnr/ffi/Pointer;Ljnr/ffi/mapper/FromNativeContext;)Ljava/lang/String; (110 bytes) @ 0x00000000027dbe94 [0x00000000027dbb20+0x374]
j  org.eclipse.swt.chromium.Chromium$Lib$jnr$ffi$0.cefswt_get_text(Ljnr/ffi/Pointer;Lorg/eclipse/swt/internal/chromium/CEF$cef_string_visitor_t;)Ljava/lang/String;+78
j  org.eclipse.swt.chromium.Chromium.updateText()V+44
j  org.eclipse.swt.chromium.Chromium.lambda$20(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;III)V+71
j  org.eclipse.swt.chromium.Chromium$$Lambda$33.invoke(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;III)V+11
j  jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$27.invoke(JJIII)V+44
v  ~StubRoutines::call_stub
J 1080  com.kenai.jffi.Foreign.invokeArrayReturnInt(JJ[B)I (0 bytes) @ 0x00000000027f625d [0x00000000027f6200+0x5d]
J 1181 C2 org.eclipse.swt.widgets.Display.readAndDispatch()Z (96 bytes) @ 0x000000000285f288 [0x000000000285e780+0xb08]
j  a.b.c.Test.main([Ljava/lang/String;)V+89
v  ~StubRoutines::call_stub
```

FYI I never saw those

```
Uncaught (in promise) TypeError
```

errors on Linux.

**Comment by dstainhauser** [comment] 2019-03-09 19:35
I get the same error on Windows 7, Java 64 bit, randomly
Using 0.8.1

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000007fefe224fa1, pid=4240, tid=0x0000000000000bc4
#
# JRE version: Java(TM) SE Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.191-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [msvcrt.dll+0x14fa1]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x00000000022be800):  JavaThread "main" [_thread_in_native, id=3012, stack(0x0000000002360000,0x0000000002460000)]

siginfo: ExceptionCode=0xc0000005, reading address 0x0000000000000100

Registers:
RAX=0x000000006e4c7900, RBX=0x000000005f1b07d8, RCX=0x0000000000000100, RDX=0x0000000000000000
RSP=0x000000000245a108, RBP=0x000000000245a1a0, RSI=0x000000000046f6a0, RDI=0x00000000f7f92818
R8 =0x000000007fffffff, R9 =0x0000000000000000, R10=0x0000000002751d84, R11=0x000000006385cb30
R12=0x0000000000000000, R13=0x000000005f1b07d8, R14=0x000000000245a1e0, R15=0x00000000022be800
RIP=0x000007fefe224fa1, EFLAGS=0x0000000000010206

Top of Stack: (sp=0x000000000245a108)
0x000000000245a108:   0000000002751db0 0000000000000000
0x000000000245a118:   000000006e4c6df6 000000000245a2b0
0x000000000245a128:   000007fee9c62e70 000000007fffffff
0x000000000245a138:   000000000245a2b0 000000000245a1a0
0x000000000245a148:   000000000245a1c0 000000000245a260
0x000000000245a158:   000000006e4c630e 000000000245a160
0x000000000245a168:   0000000000000000 000000000245a1e0
0x000000000245a178:   000000005f1b3758 0000000000000000
0x000000000245a188:   000000005f1b07d8 0000000000000000
0x000000000245a198:   000000000245a1c0 000000000245a228
0x000000000245a1a8:   0000000002737ef0 00000000e0cf3188
0x000000000245a1b8:   0000000002747a37 000000007fffffff
0x000000000245a1c8:   0000000054590090 0000000000000000
0x000000000245a1d8:   0000000000000100 0000000000000002
0x000000000245a1e8:   000000000245a1e8 000000005f3cda34
0x000000000245a1f8:   000000000245a260 000000005f3d25b8 

Instructions: (pc=0x000007fefe224fa1)
0x000007fefe224f81:   0f 84 78 ae 00 00 e8 3c 00 00 00 eb 00 48 83 c4
0x000007fefe224f91:   38 c3 90 90 90 90 90 90 90 90 90 4d 85 c0 74 0d
0x000007fefe224fa1:   38 11 74 09 48 ff c1 49 83 e8 01 75 f3 49 f7 d8
0x000007fefe224fb1:   48 1b c0 48 23 c1 c3 41 0f b6 02 83 c0 20 eb 30 


Register to memory mapping:

RAX=0x000000006e4c7900 is an unknown value
RBX={method} {0x000000005f1b07e0} 'memchr' '(JIJ)J' in 'com/kenai/jffi/Foreign'
RCX=0x0000000000000100 is an unknown value
RDX=0x0000000000000000 is an unknown value
RSP=0x000000000245a108 is pointing into the stack for thread: 0x00000000022be800
RBP=0x000000000245a1a0 is pointing into the stack for thread: 0x00000000022be800
RSI=0x000000000046f6a0 is an unknown value
RDI=0x00000000f7f92818 is an oop
com.kenai.jffi.HeapInvocationBuffer 
 - klass: 'com/kenai/jffi/HeapInvocationBuffer'
R8 =0x000000007fffffff is an unknown value
R9 =0x0000000000000000 is an unknown value
R10=0x0000000002751d84 is at code_begin+1700 in an Interpreter codelet
method entry point (kind = native)  [0x00000000027516e0, 0x00000000027527a0]  4288 bytes
R11=0x000000006385cb30 is an unknown value
R12=0x0000000000000000 is an unknown value
R13={method} {0x000000005f1b07e0} 'memchr' '(JIJ)J' in 'com/kenai/jffi/Foreign'
R14=0x000000000245a1e0 is pointing into the stack for thread: 0x00000000022be800
R15=0x00000000022be800 is a thread


Stack: [0x0000000002360000,0x0000000002460000],  sp=0x000000000245a108,  free space=1000k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [msvcrt.dll+0x14fa1]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.kenai.jffi.Foreign.memchr(JIJ)J+0
j  com.kenai.jffi.MemoryIO$UnsafeImpl.memchr(JIJ)J+4
j  com.kenai.jffi.MemoryIO.indexOf(JBI)J+6
j  jnr.ffi.provider.jffi.DirectMemoryIO.indexOf(JBI)I+12
j  jnr.ffi.provider.AbstractMemoryIO.indexOf(JB)I+5
J 8171 C2 jnr.ffi.provider.converters.StringResultConverter.fromNative(Ljnr/ffi/Pointer;Ljnr/ffi/mapper/FromNativeContext;)Ljava/lang/String; (110 bytes) @ 0x0000000003f980e0 [0x0000000003f98080+0x60]
j  org.eclipse.swt.chromium.Chromium$Lib$jnr$ffi$0.cefswt_get_text(Ljnr/ffi/Pointer;Lorg/eclipse/swt/internal/chromium/CEF$cef_string_visitor_t;)Ljava/lang/String;+78
j  org.eclipse.swt.chromium.Chromium.updateText()V+44
j  org.eclipse.swt.chromium.Chromium.lambda$20(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;III)V+71
j  org.eclipse.swt.chromium.Chromium$$Lambda$153.invoke(Lorg/eclipse/swt/internal/chromium/CEF$cef_load_handler_t;Ljnr/ffi/Pointer;III)V+11
j  jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$27.invoke(JJIII)V+44
v  ~StubRoutines::call_stub
J 7664  com.kenai.jffi.Foreign.invokeArrayO1Int32(JJ[BLjava/lang/Object;III)I (0 bytes) @ 0x0000000003e0768c [0x0000000003e07600+0x8c]
J 7663 C1 com.kenai.jffi.Invoker.invokeArrayWithObjectsInt32(JJLcom/kenai/jffi/HeapInvocationBuffer;Lcom/kenai/jffi/ObjectBuffer;)I (135 bytes) @ 0x0000000003e17c24 [0x0000000003e17660+0x5c4]
J 5246 C2 com.kenai.jffi.Invoker.invokeInt(Lcom/kenai/jffi/CallContext;JLcom/kenai/jffi/HeapInvocationBuffer;)I (42 bytes) @ 0x000000000372cb20 [0x000000000372caa0+0x80]
j  org.eclipse.swt.chromium.Chromium$Lib$jnr$ffi$0.cefswt_load_url(Ljnr/ffi/Pointer;Ljava/lang/String;[BI[Ljava/lang/String;I)V+124
j  org.eclipse.swt.chromium.Chromium.doSetUrlPost(Ljnr/ffi/Pointer;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V+60
j  org.eclipse.swt.chromium.Chromium.lambda$58(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V+16
j  org.eclipse.swt.chromium.Chromium$$Lambda$170.run()V+16
J 7434 C1 java.util.concurrent.CompletableFuture.uniRun(Ljava/util/concurrent/CompletableFuture;Ljava/lang/Runnable;Ljava/util/concurrent/CompletableFuture$UniRun;)Z (99 bytes) @ 0x0000000003d24a14 [0x0000000003d24280+0x794]
J 7607 C1 java.util.concurrent.CompletableFuture.uniRunStage(Ljava/util/concurrent/Executor;Ljava/lang/Runnable;)Ljava/util/concurrent/CompletableFuture; (62 bytes) @ 0x0000000003ddd114 [0x0000000003ddcea0+0x274]
J 7606 C1 java.util.concurrent.CompletableFuture.thenRun(Ljava/lang/Runnable;)Ljava/util/concurrent/CompletableFuture; (7 bytes) @ 0x0000000003dd6c1c [0x0000000003dd6b80+0x9c]
j  org.eclipse.swt.chromium.Chromium.doSetUrl(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Ljava/util/concurrent/CompletableFuture;+13
j  org.eclipse.swt.chromium.Chromium.setUrl(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Z+66
j  org.eclipse.swt.chromium.Browser.setUrl(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Z+19
j  org.eclipse.swt.chromium.Browser.setUrl(Ljava/lang/String;)Z+8
j  ch.ionesoft.ilp.rcp.base.RCPBrowser.setUrl(Ljava/lang/String;)Z+23
```

**Comment by danieltmartin** [comment] 2019-04-15 20:45
This seems to go away if you change the return type of [`cefswt_get_text`](https://github.com/maketechnology/chromium.swt/blob/b0b88febdde12f513360eeb888e28c4ab2f402f2/org.eclipse.swt.chromium/src/org/eclipse/swt/chromium/Chromium.java#L1450) from `String` to `void`. The corresponding Rust function is [already void](https://github.com/maketechnology/chromium.swt/blob/b0b88febdde12f513360eeb888e28c4ab2f402f2/chromium-library/chromium_swt/src/lib.rs#L456), so I think that's the cause.

**Comment by parg** [comment] 2019-04-24 16:36
Seems to be rather quiet here at the moment :( Last time I said something similar gzunino popped up to tell me otherwise, let's hope it happens again!

**Closed** 2019-04-25 03:32 UTC

**Comment by gzunino** [comment] 2019-04-25 03:54
@parg your wakeup comments works... 0.9.0 is released with this fix  :)
