### ISSUE TITLE
Any news?

### ISSUE THREAD

**Issue by dstainhauser** [maketechnology/chromium.swt#75] opened 2019-06-19 19:07 UTC
Would be great if a final release would be available

- remove debug logs in console, slows heavily down
- MacOS bug fixed with twice zoom

Beside this, Chromium is running stable and fine on Windows and can really be used for production quality.

Thanks for doing this last effort soon.

**Comment by MichaelFroeschen** [comment] 2019-06-19 19:55
I don't agree with the conclusion that this is production ready.
There are several critical issues  (at least #60, #63, #74 and basically all linux issues)  still open and the used chromium version (59) was released in early/mid 2017(!).

**Comment by dstainhauser** [comment] 2019-06-19 20:01
We don't need linux support, but I agree, could be a show stopper if you need it. 2017 could be better, but even this chromium HTML5 support is much better than XULRunner was. I don't mind using a newer one. Any progress on the project would be appreciated.

**Comment by webfolderio** [comment] 2019-06-28 19:49
This projects needs commercial support/sponsor. It's hard to release version 1.0 without proper income.

**Comment by PhaserEditor2D** [comment] 2019-07-01 04:15
Hi @webfolderio if there is not enough support/sponsor maybe you can consider a different way to get the funding. Maybe something like patreon or any other croud funding service. Is possible there are few companies or people with resources with the need of a Chromium browser, but maybe there are a lot of users intersted on contribute.

**Comment by gzunino** [comment] 2019-07-26 06:06
@PhaserEditor2D @webfolderio  any support/sponsoring is welcome! We just release 0.10.0 with many fixes. Still need to reproduce the no more handles in linux. I could not reproduce on ubuntu so far

**Closed** 2019-07-26 06:10 UTC
